name: DeployTestForPrd

on:
  push:
    branches:
      - release/*

jobs:
  test:
    name: Test Deploy
    runs-on: ubuntu-18.04
    environment: production
    steps:
      - name: deploy
        run: echo "Execute the deproy script here."
