name: DeployTest

on:
  push:
    branches:
      - develop

jobs:
  test:
    name: Test Deploy
    runs-on: ubuntu-18.04
    environment: development
    steps:
      - name: deploy
        run: echo "Execute the deproy script here."
